name: Release
on:
  push:
    branches:
      - master

jobs:
  release:
    name: Build GitHub Action
    runs-on: ubuntu-latest
    container: node:16
    steps:
    - name: Install packages
      run: apt-get update && apt-get install -y rsync git
    - uses: actions/checkout@v2.3.1
    - name: Install dependencies
      run: npm ci && npm install -g @vercel/ncc
    - name: Build release
      run: npm run build && npm run pack
    - name: Copy files to release
      run: |
        mkdir release
        cp README.md release/
        cp action.yml release/
        cp -R dist/ release/dist/
    - name: Push changes to the branch
      uses: JamesIves/github-pages-deploy-action@4.1.5
      with:
        token: ${{ secrets.PA_TOKEN }}
        branch: release
        folder: release
