on:
  push:
    branches:
      - master

jobs:
  start_scan:
    runs-on: ubuntu-latest
    name: A job to run a Nexploit scan
    steps:
    - name: Start Nexploit Scan
      id: start
      uses: NeuraLegion/run-scan@master
      with:
        api_token: ${{ secrets.NEXPLOIT_TOKEN }}
#       restart_scan: ai3LG8DmVn9Rn1YeqCNRGQ
        name: GitHub scan ${{ github.sha }}
        discovery_types: |
          [ "crawler" ]
        crawler_urls: |
          [ "https://brokencrystals.com" ]
        hosts_filter: |
          [ "https://brokencrystals.com" ]
    - name: Get the output scan url
      run: |
        echo "The scan ${{ steps.start.outputs.id }} was started on
        ${{ steps.start.outputs.url }}"
